FROM php:7.1-fpm-alpine

LABEL maintainer="Andrew Kopylov <aa74ko@gmail.com>"

# install extensions
# intl, zip, soap
RUN apk add --update --no-cache libintl icu icu-dev libxml2-dev \
  && docker-php-ext-install intl zip soap

# mcrypt, gd, iconv
RUN apk add --update --no-cache \
  freetype-dev \
  libjpeg-turbo-dev \
  libmcrypt-dev \
  libpng-dev \
  && docker-php-ext-install -j"$(getconf _NPROCESSORS_ONLN)" iconv mcrypt \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j"$(getconf _NPROCESSORS_ONLN)" gd

RUN docker-php-ext-install mbstring \
  && docker-php-ext-install exif \
  && docker-php-ext-install opcache \
  && docker-php-ext-install bcmath

# RUN pecl install mongodb \
#   && docker-php-ext-enable mongodb

RUN apk add php7-mongodb
# RUN apk add --no-cache --virtual .mongodb-ext-build-deps openssl-dev pcre-dev
# RUN apk add --update --virtual autoconf \
#   && apk add gcc libc-dev make \
#   && pecl config-set php_ini /etc/php7/php.ini \
#   && pecl install mongodb \
#   && apk del .mongodb-ext-build-deps \
#   && pecl clear-cache \
#   && docker-php-ext-enable mongodb \
#   && docker-php-source delete  

RUN echo 'date.timezone="Europe/Moscow"' >>  /usr/local/etc/php/conf.d/date.ini

WORKDIR /var/www/public/

# COPY . /html
# COPY conf/ /usr/local/etc/php-fpm.d/
CMD ["php-fpm"]
